//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FaceBasics.rc
//
#define IDI_APP                         100
#define IDD_DIALOGBAR                   103
#define IDC_TAB_1                       103
#define IDC_TAB_RECORD                  103
#define IDC_VIDEOVIEW                   1000
#define IDC_STATUS                      1001
#define IDC_BUTTON_SCREENSHOT           1002
#define IDC_BUTTON_CHOOSE_INPUT_DIRECTORY 1002
#define IDC_HD_FACE_STATUS              1003
#define IDC_RECORD_BUTTON               1004
#define IDC_FACE_RAW_EDIT_STATUS_READ   1004
#define IDC_LIST1                       1005
#define IDC_NEXT_FRAME_BUTTON           1005
#define IDC_FACE_RAW_DEPTH_STATUS       1005
#define IDC_FULL_RAW_DEPTH_STATUS       1006
#define IDC_NEXT_FRAME_BUTTON2          1006
#define IDC_BUTTON1                     1007
#define IDC_KINECT_RAW_COLOR_STATUS     1007
#define IDC_TILTANGLE_SLIDER            1007
#define IDC_KINECT_RAW_DEPTH_STATUS     1008
#define IDC_TAB2                        1009
#define IDC_HD_FACE_2D_STATUS           1009
#define IDC_EDIT1                       1010
#define IDC_FILE_PATH_EDIT_BOX          1010
#define IDC_TAB3                        1031
#define IDC_TAB1                        1034
#define IDC_RADIO1                      1035
#define IDD_APP1                        1035
#define IDD_APP_TAB                     1035
#define IDC_HD2DFACE_RADIO              1035
#define IDC_V1_COLOR_SHOW_RADIO         1035
#define IDC_SCROLLBAR1                  1036
#define IDC_TAB_PLAYBACK                1036
#define IDC_V1_R640X480_RADIO           1036
#define IDC_CHECK1                      1037
#define IDC_INFRARED_RAW_RADIO          1037
#define IDC_V1_RECORD_DEPTH_CHECK       1037
#define IDC_SLIDER1                     1038
#define IDC_DEPTH_RAW_RADIO             1038
#define IDC_LIST2                       1039
#define IDC_RECODINGS_LIST_BOX          1039
#define IDC_COMBO1                      1040
#define IDC_3D_POINTS_CLOUDS_FORMAT_COMBOX 1040
#define IDC_BUTTON2                     1041
#define IDC_FACE_RAW_DEPTH_COMBO_BOX    1041
#define IDC_BUTTON3                     1042
#define IDC_HD_FACE_COMBO_BOX           1042
#define IDC_BUTTON4                     1043
#define IDC_FULL_RAW_DEPTH_COMBO_BOX    1043
#define IDC_BUTTON5                     1044
#define IDC_HD_FACE_COMBO_BOX_THREADS   1044
#define IDC_BUTTON6                     1045
#define IDC_FACE_RAW_DEPTH_COMBO_BOX_THREADS 1045
#define IDC_FACE_RAW_DEPTH_CHECKBOX     1046
#define IDC_FULL_RAW_DEPTH_CHECKBOX     1047
#define IDC_BUTTON_CHOOSE_OUTPUT_DIRECTORY 1048
#define IDC_HDFACE_BUTTON_CHOOSE_INPUT  1049
#define IDC_RECORD_COLOR                1049
#define IDC_FACE_RAW_EDIT_BOX           1050
#define IDC_EDIT4                       1051
#define IDC_FULL_RAW_DEPTH_EDIT_BOX     1051
#define IDC_HD_FACE_CHECKBOX            1052
#define IDC_HDFACE_EDIT_BOX             1053
#define IDC_FACE_RAW_DEPTH_BUTTON_CHOOSE_INPUT 1054
#define IDC_KINECT_RAW_COLOR_CHECKBOX   1054
#define IDC_FULL_RAW_DEPTH_BUTTON_CHOOSE_INPUT 1055
#define IDC_FULL_RAW_DEPTH_COMBO_BOX_THREADS 1055
#define IDC_KINECT_RAW_COLOR_EDIT_BOX   1056
#define IDC_OUTPUT_FOLDER_LABEL         1057
#define IDC_IMAGE_FORMAT_COMBO          1057
#define IDC_PLAY_STOP_BUTTON            1058
#define IDC_KINECT_RAW_COLOR_COMBO_BOX  1058
#define IDC_HDFACE_STATUS_READ          1059
#define IDC_KINECT_RAW_COLOR_COMBO_BOX_THREADS 1059
#define IDC_FULL_RAW_DEPTH_STATUS_READ  1060
#define IDC_KINECT_RAW_DEPTH_CHECKBOX   1060
#define IDC_EDIT2                       1061
#define IDC_LIMIT_FRAMES_EDIT_BOX       1061
#define IDC_EDIT_BOX_OUTPUT_FOLDER_CONVERT 1062
#define IDC_KINECT_RAW_DEPTH_EDIT_BOX   1062
#define IDC_TAB_CONVERT                 1063
#define IDC_KINECT_DEPTH_COMBO_BOX      1063
#define IDC_KINECT_RAW_DEPTH_COMBO_BOX  1063
#define IDC_BUTTON_CONVERT              1064
#define IDC_CHECK_BOX_SINGLE_THREATED_READING 1064
#define IDC_KINECT_RAW_DEPTH_COMBO_BOX_THREADS 1064
#define IDC_EDIT_BOX_INPUT_FOLDER_CONVERT 1065
#define IDC_CENTER_CLOUDS               1065
#define IDC_BUTTON_INPUT_FOLDER_CONVERT 1066
#define IDC_HD_FACE_2D_CHECKBOX         1066
#define IDC_TEXT_LABEL_FOUND_FILES      1067
#define IDC_HDFACE_EDIT_BOX2            1067
#define IDC_HDFACE_2D_EDIT_BOX          1067
#define IDC_CHECKBOX_COLOR              1068
#define IDC_HD_FACE_2D_COMBO_BOX        1068
#define IDC_TEXT_LABEL_STATUS_READER    1069
#define IDC_HD_FACE_2D_COMBO_BOX_THREADS 1069
#define IDC_TEXT_LABEL_STATUS_WRITER    1070
#define IDC_CENTER_CLOUDS2              1070
#define IDC_LIMIT_FRAMERATE_CHECK       1070
#define IDC_LIMIT_FRAMES_CHECK          1071
#define IDC_BUTTON_OUTPUT_FOLDER_CONVERT 1072
#define IDC_LIMIT_FRAMES_EDIT_BOX2      1072
#define IDC_LIMIT_FRAMRATE_EDIT_BOX     1072
#define IDC_OUTPUT_FOLDER_LABEL2        1073
#define IDC_HD3DFACE_RADIO              1073
#define IDC_LIMIT_V2_FRAMRATE_EDIT_BOX  1073
#define IDC_COMBO_OUTPUT_FORMAT         1074
#define IDC_FACERAW_RADIO               1074
#define IDC_LIMIT_V2_FRAMERATE_CHECK    1074
#define IDC_EDIT_BOX_FILE_NAME          1075
#define IDC_FACEALL_RADIO               1075
#define IDC_COMBO_OUTPUT_FORMAT2        1076
#define IDC_COMBO_BOX_CONVERT_THREADS   1076
#define IDC_KP_FORMAT                   1076
#define IDC_SHOW_LABEL                  1077
#define IDC_COMBO_BOX_SHOW_OPT          1078
#define IDC_KINECT_ALIGNED_DEPTH_CHECKBOX 1079
#define IDC_KINECT_REMOVE_BG_CHECKBOX   1080
#define IDC_KINECT_ALIGHNED_DEPTH_COMBO_BOX_THREADS 1081
#define IDC_KINECT_ALIGHNED_DEPTH_EDIT_BOX 1082
#define IDC_KINECT_ALIGHNED_DEPTH_COMBO_BOX 1083
#define IDC_KINECT_INFRARED_CHECKBOX    1084
#define IDC_KINECT_REMOVE_BG_COLOR_CHECKBOX 1085
#define IDC_DEPTH_ALIGNED_RADIO         1085
#define IDC_INFRARED_ALIGNED_RADIO      1086
#define IDC_KINECT_INFRARED_EDIT_BOX    1087
#define IDC_INFRARED_ALL_RADIO          1088
#define IDC_KINECT_INFRARED_COMBO_BOX   1089
#define IDC_KINECT_ALIGHNED_DEPTH_STATUS 1090
#define IDC_KINECT_INFRARED_STATUS      1091
#define IDC_KINECT_KEYPOINTS_CHECKBOX   1092
#define IDC_KINECT_KEYPOINTS_STATUS     1093
#define IDC_KINECT_KEYPOINTS_COMBO_BOX_THREADS 1094
#define IDC_KINECT_KEYPOINTS_EDIT_BOX   1095
#define IDC_KINECT_KEYPOINTS_COMBO_BOX  1097
#define FACE_SHOW_GROUPBOX              1098
#define IDC_DEPTH_ALL_RADIO             1098
#define HD_FACE_SHOW_RADIO              1099
#define FIVE_KEY_POINTS_SHOW_RADIO      1100
#define IDC_RAW_COLOR_CHECK             1102
#define IDC_ALL_COM_BOX_THREADS         1103
#define IDC_RECORDING_OPT_RESET         1104
#define IDC_KEYPOINTS_CHECK             1106
#define IDC_PROGRESS1                   1107
#define IDC_RECORDING_PROGRESS          1107
#define IDC_HD2D_CHECK                  1108
#define IDC_HD3D_CHECK                  1109
#define IDC_FACE_RAW_CHECK              1110
#define IDC_KEY_POINTS_CHECK            1111
#define IDC_DEPTH_RAW_CHECK             1112
#define IDC_ALIGNED_DEPTH_CHECK         1113
#define IDC_DEPTH_3D_RAW_CHECK          1114
#define IDC_INRARED_RAW_CHECK           1115
#define IDC_ALIGNED_INFRARED_CHECK      1116
#define IDC_GROUP_SHOW_OPT              1117
#define IDC_V1_DEPTH_SHOW_RADIO         1118
#define IDC_V1_INFRARED_SHOW_RADIO      1119
#define IDC_V1_R320X240_RADIO           1120
#define IDC_GROUP_SHOW_OPT2             1121
#define IDC_STATIC_V2_SHOW_             1122
#define IDC_STATIC_V2_SHOW              1122
#define IDC_V1_SHOW_TYPE_STATIC         1123
#define IDC_V1_SHOW_RESOLUTION_STATIC   1124
#define IDC_V1_RECORD_INFRARED_CHECK    1126
#define IDC_V1_RECORDING_ALIGNED_CHECKBOX 1128
#define IDC_RECORDING_V1_ENABLE_CHECK   1129
#define IDC_RECORDING_V2_ENABLE_CHECK   1133
#define IDC_RECORDING_OPT_V1            1135
#define IDC_RECORDING_OPT_V2            1136
#define IDC_STATIC_INFRARED_V2          1137
#define IDC_STATIC_DEPTH_V2             1138
#define IDC_STATIC_KEYPOINTS_V2         1139
#define IDC_V1_SHOW_TYPE_COMBO          1143
#define IDC_V1_COLOR_RECORDING_TYPE_COMBO 1144
#define IDC_V1_RECORDING_COLOR_CHECK    1145
#define IDC_V1_DEPTH_RECORDING_TYPE_COMBO 1146
#define IDC_ANGLE_STATUS                1147
#define IDC_MAX_STATIC                  1148
#define IDC_MIN_STATIC                  1149
#define IDC_V1_FPS_COMBO                1150
#define IDC_CHECK2                      1151
#define IDC_V1_REMOVE_BG_CHECK          1151
#define IDC_KINECT_INFRARED_COMBO_BOX_THREADS 1806
#define IDC_PLAY_PAUSE_BUTTON           1807
#define IDC_PLAY_PAUSE_BUTTON2          1808
#define IDC_PLAY_PREV_FRAME_BUTTON      1809
#define IDC_PLAY_NEXT_FRAME_BUTTON3     1810
#define IDC_PLAY_PREV_FRAME_BUTTON2     1810
#define IDC_PLAY_NEXT_FRAME_BUTTON      1811
#define IDC_LIMIT_PLAYBACK_FRAMRATE_EDIT_BOX 1812
#define IDC_LIMIT_PLAYBACK_FRAMERATE_CHECK 1813
#define IDC_PLAYBACK_SLIDER             1814
#define IDC_PLAY_NEXT_FRAME_BUTTON2     1815
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
